name: Open Weekly Issue

on:
  schedule:
    - cron: '44 15 * * 1' 

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: imjohnbo/issue-bot@v3
        with:
          title: "Weekly Report for $(date +'%Y-%m-%d')"
          body: |
            This is the weekly report issue.
          labels: |
            weekly-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

